import type { BibleStudyLessonSummary, BibleStudySeriesDetail } from "./data";

const newTestamentSource = [
  {
    slug: "new-testament-overview",
    title: "New Testament Overview",
    summary: "Begin with the big picture of the New Testament, tracing how the story of Jesus, the early Church, the apostolic letters, and Revelation continue and fulfill the biblical story introduced in the Old Testament.",
    bibleProjectUrl: "https://bibleproject.com/videos/new-testament-overview/",
    streamSrc: "https://stream.mux.com/Z023UIyqQF6RzvxYo02tMKBqlUrWdWpingO02VYDgWzQPY/high.mp4?download=new-testament-overview.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/00_NT%20Overview.jpg",
  },
  {
    slug: "matthew-1-13",
    title: "Matthew 1-13",
    summary: "Explore the opening half of Matthew as Jesus is presented as Israel’s promised Messiah and King, teaching about God’s Kingdom and demonstrating its arrival through His words and works.",
    bibleProjectUrl: "https://bibleproject.com/videos/matthew-1-13/",
    streamSrc: "https://stream.mux.com/801erPO5siagtLvyNYBB01nIS8GRD4ZQFUgLPEPb2Vc2Y/high.mp4?download=matthew-1-13.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/42-Matthew-FNL-1.jpg",
  },
  {
    slug: "matthew-14-28",
    title: "Matthew 14-28",
    summary: "Continue through Matthew as Jesus moves toward Jerusalem, confronts opposition, gives His life, rises from the dead, and commissions His followers to make disciples among the nations.",
    bibleProjectUrl: "https://bibleproject.com/videos/matthew-14-28/",
    streamSrc: "https://stream.mux.com/l26rKhJazSPaf0201RS8aLbe9bTF47R2yx021kYKHVzyVI/high.mp4?download=matthew-14-28.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/42-Matthew-FNL-1.jpg",
  },
  {
    slug: "mark",
    title: "Mark",
    summary: "Follow Mark’s fast-moving account of Jesus’ ministry, suffering, death, and resurrection as the Gospel steadily reveals the identity of Jesus and what it means to follow Him.",
    bibleProjectUrl: "https://bibleproject.com/videos/mark/",
    streamSrc: "https://stream.mux.com/e9eTDZe5OFaz22dp2Llh8srfxP2unSimWnUIZVq202Os/high.mp4?download=mark.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/44-Mark-FNL.jpg",
  },
  {
    slug: "luke-1-9",
    title: "Luke 1-9",
    summary: "Explore the opening movement of Luke as Jesus is introduced as the promised Savior and begins announcing God’s Kingdom through teaching, healing, forgiveness, and compassion for those often overlooked.",
    bibleProjectUrl: "https://bibleproject.com/videos/luke-1-9/",
    streamSrc: "https://stream.mux.com/stejN00X6iFAutx7foc902ijNyO11r7gch8gNMnzGVLBM/high.mp4?download=luke-1-9.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/47-48-Luke-FNL.jpg",
  },
  {
    slug: "luke-10-24",
    title: "Luke 10-24",
    summary: "Continue through Luke as Jesus journeys toward Jerusalem, teaches about faithful discipleship, gives His life, rises again, and opens the Scriptures to His followers.",
    bibleProjectUrl: "https://bibleproject.com/videos/luke-10-24/",
    streamSrc: "https://stream.mux.com/00zzJzUdTCefLs01DFvfNKmW5f00YXkovQl01PHvJyTJjhY/high.mp4?download=luke-10-24.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/47-48-Luke-FNL.jpg",
  },
  {
    slug: "john-1-12",
    title: "John 1-12",
    summary: "Study the first half of John as Jesus is revealed through His signs, claims, and encounters as the eternal Word, Messiah, Son of God, and giver of life.",
    bibleProjectUrl: "https://bibleproject.com/videos/john-1-12/",
    streamSrc: "https://stream.mux.com/sC6VzZQDk3024mhE2n8csZLINmtu7Vew8sgEs2W01V01gg/high.mp4?download=john-1-12.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/45-46-john-1.jpg",
  },
  {
    slug: "john-13-21",
    title: "John 13-21",
    summary: "Continue through John as Jesus prepares His disciples for His departure, goes to the cross, rises from the dead, and commissions His followers to continue His mission.",
    bibleProjectUrl: "https://bibleproject.com/videos/john-13-21/",
    streamSrc: "https://stream.mux.com/THgfzaH02VR5sEqbks815HtAvqp02ecinrwLaQmw3b6LM/high.mp4?download=john-13-21.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/45-46-john-1.jpg",
  },
  {
    slug: "acts-1-12",
    title: "Acts 1-12",
    summary: "See how the risen Jesus continues His work through the Holy Spirit as the gospel moves from Jerusalem outward and the early Church takes shape amid growth, opposition, and mission.",
    bibleProjectUrl: "https://bibleproject.com/videos/acts-1-12/",
    streamSrc: "https://stream.mux.com/zEm8b16B4p7NWXnDvS5nu25nSExRoI6EKP5GhHAWg2Q/high.mp4?download=acts-1-12.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/49-Acts-FNL.jpg",
  },
  {
    slug: "acts-13-28",
    title: "Acts 13-28",
    summary: "Follow the second half of Acts as the gospel crosses cultural and geographic boundaries through missionary journeys, church planting, persecution, and Paul’s witness all the way to Rome.",
    bibleProjectUrl: "https://bibleproject.com/videos/acts-13-28/",
    streamSrc: "https://stream.mux.com/JGLOuBLC800dwIB2EWj027EN9e6K42poyigmI600moX00008/high.mp4?download=acts-13-28.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/49-Acts-FNL.jpg",
  },
  {
    slug: "romans-1-4",
    title: "Romans 1-4",
    summary: "Explore the opening of Romans as Paul explains humanity’s universal need for salvation and announces justification through faith in Jesus Christ apart from boasting in human works.",
    bibleProjectUrl: "https://bibleproject.com/videos/romans-1-4/",
    streamSrc: "https://stream.mux.com/JOwtd4wJBaE4tNEpG29osk7YpsfJGd1hvFP9RL2nPWY/high.mp4?download=romans-1-4.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/50_Romans.jpg",
  },
  {
    slug: "romans-5-16",
    title: "Romans 5-16",
    summary: "Continue through Romans as Paul develops the implications of the gospel for new life in Christ, life in the Spirit, God’s faithfulness, Christian unity, and faithful living.",
    bibleProjectUrl: "https://bibleproject.com/videos/romans-5-16/",
    streamSrc: "https://stream.mux.com/01O8p00kAKeMNeSBelNy100lSoMoFcCZ01W6rU1McatNQ8w/high.mp4?download=romans-5-16.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/50_Romans.jpg",
  },
  {
    slug: "1-corinthians",
    title: "1st Corinthians",
    summary: "Study Paul’s first letter to Corinth as he addresses division, holiness, worship, spiritual gifts, love, and the resurrection within a troubled but deeply gifted church.",
    bibleProjectUrl: "https://bibleproject.com/videos/1-corinthians/",
    streamSrc: "https://stream.mux.com/WieKKhX26bqP4x9OKvQUmBKSHvk38EcEeTilyn5lXP4/high.mp4?download=1-corinthians.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/52-53-Corinthians.jpg",
  },
  {
    slug: "2-corinthians",
    title: "2nd Corinthians",
    summary: "Explore 2 Corinthians as Paul describes Christian ministry through the pattern of the cross, showing how God’s power is often displayed through weakness, suffering, generosity, and reconciliation.",
    bibleProjectUrl: "https://bibleproject.com/videos/2-corinthians/",
    streamSrc: "https://stream.mux.com/XoW027eYYCX1FQvly9RAOIeH02KL012t4n2L3B1IosUSyI/high.mp4?download=2-corinthians.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/53-2-Corinthians-FNL2.jpg",
  },
  {
    slug: "galatians",
    title: "Galatians",
    summary: "Study Galatians as Paul defends the gospel of grace, explains justification through faith in Christ, and calls believers to live in the freedom and transforming power of the Holy Spirit.",
    bibleProjectUrl: "https://bibleproject.com/videos/galatians/",
    streamSrc: "https://stream.mux.com/4IfSvOSllmXJrS81fhXR01HAs7zscrlEX9r4D9F9M4dg/high.mp4?download=galatians.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/54-Galatians-FNL.jpg",
  },
  {
    slug: "ephesians",
    title: "Ephesians",
    summary: "Explore Ephesians as Paul celebrates God’s work in Christ to create one new people and then calls believers to live out that unity through holiness, love, maturity, and spiritual faithfulness.",
    bibleProjectUrl: "https://bibleproject.com/videos/ephesians/",
    streamSrc: "https://stream.mux.com/fBwEIh2ZQL901mFJZAw7f02aRqFRHNdinm8w1T01m023I02M/high.mp4?download=ephesians.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/55-Ephesians-FNL.jpg",
  },
  {
    slug: "philippians",
    title: "Philippians",
    summary: "Study Philippians as Paul writes from imprisonment about joy, humility, faithful partnership, perseverance, and a life shaped by the self-giving example of Jesus Christ.",
    bibleProjectUrl: "https://bibleproject.com/videos/philippians/",
    streamSrc: "https://stream.mux.com/02ih3eMgX8BhfWNCQvCAAx64o6tp702Y300pspD00KtyHqY/high.mp4?download=philippians.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/56-Philippians-FNL.jpg",
  },
  {
    slug: "colossians",
    title: "Colossians",
    summary: "Explore Colossians as Paul presents the supremacy and sufficiency of Christ and calls believers to live as people made new through union with Him.",
    bibleProjectUrl: "https://bibleproject.com/videos/colossians/",
    streamSrc: "https://stream.mux.com/V01bN4sEe00pnK3q3dpeTcXb76puDljNGzQVXljgz8BZA/high.mp4?download=colossians.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/57%20Colossians%20PRF.jpg",
  },
  {
    slug: "philemon",
    title: "Philemon",
    summary: "Study Paul’s brief letter to Philemon as the gospel reshapes relationships, forgiveness, brotherhood, and the way believers are called to receive one another in Christ.",
    bibleProjectUrl: "https://bibleproject.com/videos/philemon/",
    streamSrc: "https://stream.mux.com/LX1qiBymc001VKGvwvsYPVStla01c02cjs8gYr2XoJns01c/high.mp4?download=philemon.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/58-Philemon-FNL-1.jpg",
  },
  {
    slug: "1-thessalonians",
    title: "1st Thessalonians",
    summary: "Explore 1 Thessalonians as Paul encourages a young church to remain faithful in holiness, love, perseverance, and hope while awaiting the return of Jesus.",
    bibleProjectUrl: "https://bibleproject.com/videos/1-thessalonians/",
    streamSrc: "https://stream.mux.com/fUgStG3Nmi01m62gSgztdausKS186QWKC1ElQSrxHTPo/high.mp4?download=1-thessalonians.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/59a-1-Thessalonians-FNL.jpg",
  },
  {
    slug: "2-thessalonians",
    title: "2nd Thessalonians",
    summary: "Study 2 Thessalonians as Paul strengthens believers facing confusion and pressure, calling them to steady faith, patient endurance, and confidence in God’s final justice.",
    bibleProjectUrl: "https://bibleproject.com/videos/2-thessalonians/",
    streamSrc: "https://stream.mux.com/s8xNyy92ChSWhjehfSxREYKI5KsrGGZcnPTwVp8gKJ4/high.mp4?download=2-thessalonians.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/59b-2-Thessalonians-FNL.jpg",
  },
  {
    slug: "1-timothy",
    title: "1st Timothy",
    summary: "Explore 1 Timothy as Paul instructs Timothy about sound teaching, church leadership, worship, godly conduct, and faithful care for the Christian community.",
    bibleProjectUrl: "https://bibleproject.com/videos/1-timothy/",
    streamSrc: "https://stream.mux.com/vP00JOsZ45owxi02N7fGK8rN1J3BBRXND3RX7ucUMBjO00/high.mp4?download=1-timothy.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/60-1-Timothy-FNL.jpg",
  },
  {
    slug: "2-timothy",
    title: "2nd Timothy",
    summary: "Study 2 Timothy as Paul gives final encouragement to remain faithful to Christ, guard the gospel, endure hardship, and pass biblical truth on to trustworthy believers.",
    bibleProjectUrl: "https://bibleproject.com/videos/2-timothy/",
    streamSrc: "https://stream.mux.com/CPH011Q2nQ8jLVAKmU4n4fKWcP9lCbHLgT6pSsVlv5iw/high.mp4?download=2-timothy.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/61-2-Timothy-FNL.jpg",
  },
  {
    slug: "titus",
    title: "Titus",
    summary: "Explore Titus as Paul connects sound doctrine with transformed character, healthy church leadership, good works, and a public witness shaped by God’s grace.",
    bibleProjectUrl: "https://bibleproject.com/videos/titus/",
    streamSrc: "https://stream.mux.com/yS7D01WgY23OXviV6oFm01ds6XMB4Xh02fmPwMiuxUZq018/high.mp4?download=titus.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/62%20Titus%20FNL.jpg",
  },
  {
    slug: "hebrews",
    title: "Hebrews",
    summary: "Study Hebrews as it presents the greatness of Jesus, the fulfillment of the old covenant patterns, and a sustained call for believers to endure in faith and draw near to God through Christ.",
    bibleProjectUrl: "https://bibleproject.com/videos/hebrews/",
    streamSrc: "https://stream.mux.com/8dq3itoij1p9Uuydyk2joy9skBhO00N00SrPrL020001Q8i8/high.mp4?download=hebrews.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/63-Hebrews-FNL.jpeg",
  },
  {
    slug: "james",
    title: "James",
    summary: "Explore James as practical wisdom for a mature Christian life, emphasizing endurance, obedience, speech, humility, prayer, and a faith that is demonstrated through action.",
    bibleProjectUrl: "https://bibleproject.com/videos/james/",
    streamSrc: "https://stream.mux.com/qhwIsZal01vnXbXQUiLeY00LOdUML2HtPXMnH8PgRAZf00/high.mp4?download=james.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/64-James_FNL.jpg",
  },
  {
    slug: "1-peter",
    title: "1st Peter",
    summary: "Study 1 Peter as an encouragement to Christians living under pressure, calling them to holiness, hope, faithful witness, and Christlike endurance in suffering.",
    bibleProjectUrl: "https://bibleproject.com/videos/1-peter/",
    streamSrc: "https://stream.mux.com/cgex91dCChkk6bl6oDZAT6KvJZREDYC1MSVKyTqLdKk/high.mp4?download=1-peter.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/65-1-Peter-FNL.jpg",
  },
  {
    slug: "2-peter",
    title: "2nd Peter",
    summary: "Explore 2 Peter as a final appeal to grow in Christlike character, resist corrupt teaching, remember apostolic truth, and live faithfully in light of the promised Day of the Lord.",
    bibleProjectUrl: "https://bibleproject.com/videos/2-peter/",
    streamSrc: "https://stream.mux.com/mlymhw6hBY2vK1ZYO00Dfwmnz0000G7KoCOPINAmMDDJzw/high.mp4?download=2-peter.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/66-2-Peter-FNL.jpg",
  },
  {
    slug: "1-3-john",
    title: "1-3 John",
    summary: "Study the letters of John as they emphasize the truth about Jesus Christ, assurance of faith, obedience, discernment, and the inseparable connection between knowing God and loving one another.",
    bibleProjectUrl: "https://bibleproject.com/videos/1-3-john/",
    streamSrc: "https://stream.mux.com/3Kp22zNH5QhX027LKFYSknh1fmOGtYkekaPFYY5hFg5c/high.mp4?download=1-3-john.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/67-123-John.jpg",
  },
  {
    slug: "jude",
    title: "Jude",
    summary: "Explore Jude’s urgent call for believers to contend for the faith, reject corrupt teaching, remember God’s judgment on rebellion, and remain grounded in His mercy and truth.",
    bibleProjectUrl: "https://bibleproject.com/videos/jude/",
    streamSrc: "https://stream.mux.com/W01i5s0102PiKfdLNO1E9zNThUN9N1FWyMCqVLSTYk7dnI/high.mp4?download=jude.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/68-Jude-FNL.jpg",
  },
  {
    slug: "revelation-1-11",
    title: "Revelation 1-11",
    summary: "Begin Revelation by exploring its apocalyptic imagery, messages to the churches, vision of God’s throne, and the Lamb whose victory redefines power through faithful witness and sacrifice.",
    bibleProjectUrl: "https://bibleproject.com/videos/revelation-1-11/",
    streamSrc: "https://stream.mux.com/005Ha01v65P4LM02xcsTbyW902oAThsAtuSRaCHnNedC01Dk/high.mp4?download=revelation-1-11.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/69-70-Revelation-FNL%20(1).jpg",
  },
  {
    slug: "revelation-12-22",
    title: "Revelation 12-22",
    summary: "Continue through Revelation as its symbols point toward the defeat of evil, the final judgment, the victory of Jesus, and the biblical story’s closing vision of a renewed creation where God dwells with His people.",
    bibleProjectUrl: "https://bibleproject.com/videos/revelation-12-22/",
    streamSrc: "https://stream.mux.com/4hFy6Fg00v5OZH7ThE8s4JSZ02i3bfCexbCCyXGybUTK00/high.mp4?download=revelation-12-22.mp4",
    imageSrc: "https://resources.faithchangeseverything.org/images/New%20Testement/69-70-Revelation-FNL.jpg",
  },
] as const;

export const newTestamentLessons: BibleStudyLessonSummary[] = newTestamentSource.map((lesson) => ({
  slug: lesson.slug,
  title: lesson.title,
  summary: lesson.summary,
  href: `/bible-studies/new-testament/${lesson.slug}`,
  imageSrc: lesson.imageSrc,
  imageAlt: `BibleProject overview illustration for ${lesson.title}`,
  video: {
    title: lesson.title,
    description: `Watch the BibleProject overview for ${lesson.title} and see how this book or section contributes to the message and structure of the New Testament.`,
    href: lesson.bibleProjectUrl,
    streamSrc: lesson.streamSrc,
    ownerName: "BibleProject",
    ownerUrl: "https://bibleproject.com/",
    attribution: "BibleProject is the author and owner of this video.",
  },
}));

export const newTestamentSeriesDetail: BibleStudySeriesDetail = {
  slug: "new-testament",
  title: "New Testament",
  introduction:
    "This 32-video series walks through the New Testament from its opening overview to Revelation, helping visitors understand the setting, authorship, structure, and central message of each book or major section while seeing how the whole New Testament centers on Jesus Christ.",
  overviewTitle: "Understanding the New Testament",
  lessonsTitle: "Explore the New Testament",
  lessonsDescription:
    "Begin with the New Testament overview, then continue through the books and major sections in order. Several books are covered in two videos, and those paired lessons intentionally use the same artwork while remaining separate studies.",
  pastorIntroduction: {
    title: "A Personal Introduction from Pastor Richard",
    excerpt:
      "The New Testament tells us the story of Jesus Christ, the beginning of the Church, and the message of salvation carried into the world by those who followed Him. This series is designed to help you understand that larger story one book and section at a time. As you move through these videos, keep your Bible with you, pause when something catches your attention, read the passages being discussed for yourself, and ask God to help you understand His Word and apply what you are learning to your life.",
    imageSrc: "/images/pastor-richard.png",
    videoEmbedUrl:
      "https://customer-r3nvd2sbu94qp82j.cloudflarestream.com/fdfb3ceb95ddca131adef9a92d5ff84a/iframe",
    compactLayout: true,
  },
  lessons: newTestamentLessons,
  sourceNote:
    "The teaching videos in this series are provided by BibleProject. BibleProject is the author and owner of each video, and attribution appears on every individual lesson page. No FCE transcript or supporting document is provided for this series.",
};
