import type { SupportIconName } from "./SupportIcon";

export type SupportResource={title:string;description:string;href:string;note?:string};
export type SupportCategory={id:string;title:string;description:string;icon:SupportIconName;resources:SupportResource[]};
export const crisisSupport={us:{name:"988 Suicide & Crisis Lifeline",callHref:"tel:988",textHref:"sms:988",chatHref:"https://988lifeline.org/chat/",websiteHref:"https://988lifeline.org/"},canada:{name:"9-8-8: Suicide Crisis Helpline",callHref:"tel:988",textHref:"sms:988",websiteHref:"https://988.ca/"}} as const;
export const supportCategories:SupportCategory[]=[
{id:"christian-counseling",title:"Christian Counseling",description:"Christian counseling resources and ways to connect with counselors.",icon:"counseling",resources:[{title:"American Association of Christian Counselors (AACC)",description:"Christian counseling resources and professional network.",href:"https://aacc.net/"},{title:"Focus on the Family — Christian Counselors Network",description:"Find a counselor through Focus on the Family's Christian counselor network.",href:"https://www.focusonthefamily.com/christian-counselors-network/"},{title:"Christian Counseling & Educational Foundation (CCEF)",description:"Biblical counseling resources, training, and counseling information.",href:"https://www.ccef.org/counseling/"},{title:"Association of Certified Biblical Counselors (ACBC)",description:"Biblical counseling resources and counselor directory.",href:"https://biblicalcounseling.com/",note:"A complementary biblical-counseling resource, not a replacement for licensed mental-health care when professional treatment is needed."}]},
{id:"mental-health",title:"Mental Health Resources",description:"Education, support, referrals, crisis information, and treatment-finding resources.",icon:"mental-health",resources:[{title:"National Alliance on Mental Illness (NAMI)",description:"Mental-health education, support, local affiliates, and resources.",href:"https://www.nami.org/"},{title:"Mental Health America (MHA)",description:"Mental-health education, screening tools, and information about finding help.",href:"https://mhanational.org/"},{title:"988 Suicide & Crisis Lifeline",description:"Immediate U.S. crisis support by call, text, or chat.",href:"https://988lifeline.org/"},{title:"SAMHSA",description:"U.S. mental-health and substance-use information and treatment resources.",href:"https://www.samhsa.gov/find-help"},{title:"FindTreatment.gov",description:"Confidential U.S. treatment locator for mental-health and substance-use services.",href:"https://findtreatment.gov/"}]},
{id:"grief-recovery",title:"Grief & Recovery Ministries",description:"Christ-centered support for grief, loss, hurts, habits, and recovery.",icon:"grief",resources:[{title:"GriefShare",description:"Biblically based grief-recovery groups hosted by churches.",href:"https://www.griefshare.org/"},{title:"Celebrate Recovery",description:"Christ-centered recovery support for hurts, habits, and addictions.",href:"https://celebraterecovery.com/"}]},
{id:"marriage-family",title:"Marriage & Family",description:"Biblically grounded resources for marriage, parenting, family life, and relationship support.",icon:"family",resources:[{title:"Focus on the Family",description:"Marriage, parenting, family, and counseling resources.",href:"https://www.focusonthefamily.com/"},{title:"FamilyLife",description:"Resources for marriage, parenting, and family discipleship.",href:"https://www.familylife.com/"},{title:"Hope Restored",description:"Christian marriage intensives for couples experiencing serious relationship distress.",href:"https://hoperestored.focusonthefamily.com/"},{title:"Love and Respect Ministries",description:"Biblical marriage and relationship resources.",href:"https://www.loveandrespect.com/"},{title:"The Gospel Coalition — Marriage",description:"Biblical articles and resources addressing marriage and family life.",href:"https://www.thegospelcoalition.org/topics/marriage/"}]},
{id:"addiction-recovery",title:"Addiction Recovery",description:"Faith-based and professional pathways for substance-use concerns, addiction, and recovery.",icon:"recovery",resources:[{title:"Celebrate Recovery",description:"Christ-centered recovery support offered through churches and groups.",href:"https://celebraterecovery.com/"},{title:"Pure Desire Ministries",description:"Christian resources addressing pornography and sexual brokenness for individuals, spouses, and churches.",href:"https://puredesire.org/"},{title:"The Salvation Army Adult Rehabilitation Centers",description:"Faith-based residential rehabilitation programs and recovery support.",href:"https://www.salvationarmyusa.org/usa-central-territory/adult-rehabilitation-centers/"},{title:"SAMHSA Treatment Locator",description:"Find U.S. treatment for substance-use and mental-health needs.",href:"https://www.samhsa.gov/find-help/locators"}]},
{id:"bible-study",title:"Bible Study & Understanding Scripture",description:"Resources for people who want to read, study, and understand God's Word more deeply.",icon:"bible",resources:[{title:"FCE Bible Study Resources",description:"Faith Changes Everything Bible-study guidance and recommended study resources.",href:"/resources"}]},
{id:"find-a-church",title:"Finding a Church",description:"Guidance for finding a healthy, Bible-believing local church and taking the next step into Christian community.",icon:"church",resources:[{title:"Find a Church Home",description:"FCE guidance for what to look for in a healthy local church.",href:"/find-a-church"}]}
];